package: guinavigation
version: '1.0.0 Beta 1'
author: 'Stefan Frank'
supportpage: www.redaxo.org/de/forum/


page:
    title: translate:guinav_name
    perm: guinavigation[]
    pjax: true
    icon: rex-icon fa-link
    subpages:
        static: { title: translate:guinav_static }
        context: { title: translate:guinav_context }
        simple: { title: translate:guinav_simple }
        langswitch: { title: translate:guinav_langswitch }
        breadcrumb: { title: translate:guinav_breadcrumb }
        info: { title: translate:guinav_info }

requires:
    php: 
        php: '>= 5.5'
    redaxo: ^5.2.0
    packages: 
        yform:'^2.1'

