package: guinavigation
version: '1.0.1'
author: 'Stefan Frank'
supportpage: https://github.com/ichbeigit/GUINavigation


page:
    title: translate:guinav_name
    perm: guinavigation[]
    pjax: true
    icon: rex-icon fa-link
    subpages:
        static: { title: translate:guinav_static }
        context: { title: translate:guinav_context }
        simple: { title: translate:guinav_simple }
        lang: { title: translate:guinav_lang }
        breadcrumb: { title: translate:guinav_breadcrumb }
        info: { title: translate:guinav_info }
        code: { title: translate:guinav_code }

requires:
    php: 
        php: '>= 5.5'
    redaxo: ^5.2.0
    packages: 
        yform:'^2.1'

